name: ci package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  fintoc-package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      - name: Disable telemetry
        run: flutter --disable-telemetry

      - id: install
        name: Install dependencies
        run: flutter pub get

      - name: Check formatting
        run: dart format --output=none --set-exit-if-changed .
        if: always() && steps.install.outcome == 'success'

      - name: Analyze project source
        run: dart analyze --fatal-warnings --fatal-infos .
        if: always() && steps.install.outcome == 'success'

      - id: coverage
        name: Install coverage
        run: dart pub global activate coverage
        if: always() && steps.install.outcome == 'success'
    
      - name: Running tests with coverage
        run: dart pub global run coverage:test_with_coverage
        if: always() && steps.coverage.outcome == 'success'

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3

      - name: Publish project
        run: flutter pub publish --dry-run
        if: always() && steps.install.outcome == 'success'
