name: ci package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  fintoc-package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - id: install
        name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      - name: Disable telemetry
        run: flutter --disable-telemetry

      - id: dependencies
        name: Install dependencies
        run: flutter pub get

      - id: formatting
        name: Check formatting
        run: dart format --output=none --set-exit-if-changed .
        if: always() && steps.dependencies.outcome == 'success'

      - id: analyze
        name: Analyze project source
        run: dart analyze --fatal-warnings --fatal-infos .
        if: always() && steps.formatting.outcome == 'success'

      - id: test
        name: Install test
        run: flutter test --coverage
        if: always() && steps.analyze.outcome == 'success'

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        if: always() && steps.test.outcome == 'success'

      - name: Publish project
        run: flutter pub publish --dry-run
        if: always() && steps.test.outcome == 'success'
