# A CI configuration to auto-publish pub packages.
name: ci publish # publish to pub.dev

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*' # tag-pattern on pub.dev: '1.0.0'

permissions:
  id-token: write

# Publish using the reusable workflow from dart-lang.
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Publish project
        uses: sakebook/actions-flutter-pub-publisher@v1.4.1
        with:
          credential: ${{ secrets.GOOGLE_ACCOUNT_CREDENTIALS }}
          flutter_package: false
          skip_test: true
