# A CI configuration to auto-publish pub packages.
name: ci publish # publish to pub.dev

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*' # tag-pattern on pub.dev: '1.0.0'

permissions:
  id-token: write

# Publish using the reusable workflow from dart-lang.
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - id: install
        name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      - name: Disable telemetry
        run: flutter --disable-telemetry

      - id: dependencies
        name: Install dependencies
        run: flutter pub get

      - name: Publish project
        run: flutter pub publish
        if: always() && steps.dependencies.outcome == 'success'
